# Docker Test Environment
# > Not required, but I used this to test the project.
# - Creates a reproducible environment for testing this project.
#
# To access the application,
# - Port 80 for the project
# - Port 8081 for PhpMyAdmin to view the database

services:
    database:
        image: 'mysql:latest'
        healthcheck:
            test: 'mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD'
            start_period: 0s
            interval: 1s
            timeout: 1s
            retries: 60
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
    make_db:
        image: 'mysql:latest'
        depends_on:
            database:
                condition: service_healthy
        command: 'mysql -u root -h database -P 3306 --password=password -e "CREATE DATABASE IF NOT EXISTS `tti_challenge`;"'
    pma:
        image: 'phpmyadmin/phpmyadmin:latest'
        ports:
            - '8081:80'
        environment:
            PMA_HOST: 'database'
            PMA_USER: 'root'
            PMA_PASSWORD: 'password'
        depends_on:
            - database
        links:
            - database
    project:
        build: ./
        ports:
            - '80:80'
        environment:
            SETUPCMD: 'git config --global --add safe.directory /home/container/app'
            PRECMD: 'cd /home/container/app && php artisan migrate --force && php artisan db:seed --class=ChallengeSeeder --force'
            #APP_ENV: 'local'
            DB_CONNECTION: 'mysql'
            DB_HOST: 'database'
            DB_PORT: 3306
            DB_USERNAME: 'root'
            DB_PASSWORD: 'password'
            DB_DATABASE: 'tti_challenge'
            APP_KEY: 'base64:o6LXrnKO/cuCWizMSocaYxfaXqnBw1gkhP5EObcf3Bo=' # a sample key
            APP_URL: 'http://localhost'
        depends_on:
            database:
                condition: service_healthy
        stdin_open: true
        links:
            - database
